// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKfCmypaxR6tiIfRdffIZFPzWvLHrsbFw',
    appId: '1:776051764050:web:d0a1adfbe2255cd430688b',
    messagingSenderId: '776051764050',
    projectId: 'weather-df44c',
    authDomain: 'weather-df44c.firebaseapp.com',
    storageBucket: 'weather-df44c.firebasestorage.app',
    measurementId: 'G-8TX9H64S8J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBzeMw_gTYcDsJScBS2OsTMw_MyQO2bI',
    appId: '1:776051764050:ios:035ef9fb931eb03b30688b',
    messagingSenderId: '776051764050',
    projectId: 'weather-df44c',
    storageBucket: 'weather-df44c.firebasestorage.app',
    iosBundleId: 'com.weatherapp.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBzeMw_gTYcDsJScBS2OsTMw_MyQO2bI',
    appId: '1:776051764050:ios:035ef9fb931eb03b30688b',
    messagingSenderId: '776051764050',
    projectId: 'weather-df44c',
    storageBucket: 'weather-df44c.firebasestorage.app',
    iosBundleId: 'com.weatherapp.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKfCmypaxR6tiIfRdffIZFPzWvLHrsbFw',
    appId: '1:776051764050:web:d0a1adfbe2255cd430688b',
    messagingSenderId: '776051764050',
    projectId: 'weather-df44c',
    authDomain: 'weather-df44c.firebaseapp.com',
    storageBucket: 'weather-df44c.firebasestorage.app',
    measurementId: 'G-8TX9H64S8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZdx1ppc5e9BA5PPIaV7Y6eFLNP0vlMHo',
    appId: '1:776051764050:android:a79a7907bedeef0f30688b',
    messagingSenderId: '776051764050',
    projectId: 'weather-df44c',
    storageBucket: 'weather-df44c.firebasestorage.app',
  );

}